apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  namespace: production
  labels:
    role: app
spec:
  replicas: 3
  selector:
    matchLabels:
      role: app
  template:
    metadata:
      labels:
        role: app

    spec:
      containers:
      - image: webserver:latest 
        name: webserver
        ports:
        - containerPort: 8181
